---

- hosts: all
  become: true
  tasks:

 

  - name: install apache, Php and update cache package!!!
    yum:
      name:
       - httpd
       - php
      state: latest 
      update_cache: yes
    when: ansible_distribution == "CentOS"  

 
