---

- hosts: all
  become: true
  tasks:

  - name: update Repos index
    yum: 
      update_cache: yes

  - name: install apache2 package
    yum:
      name: httpd
      state: absent 


  - name: add php support for apcahe
    yum:
      name: php
      state: absent
