---

- hosts: all
  become: true
  tasks:


  - name : cache  updates (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"




-  hosts: all
   become: true
   roles: 
     - base
             


- hosts: web_server
  become: true
  roles: 
    - web_server

     

- hosts: db_server
  become: true
  roles: 
    - db_server




- hosts: workstation
  become: true
  roles:
    - workstation 
   




    
     
