---

- hosts: all
  become: true
  tasks:


  - name : install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"




- hosts: web_server
  become: true
  tasks: 
 

  - name: install apache, Php and update cache package!!!

    tags: apache, httpd, centos
    yum:
      name:
       - httpd
       - php
      state: latest 
    when: ansible_distribution == "CentOS"  

 


- hosts: db_server
  become: true
  tasks: 



  - name: install maria db package (CentOS)
    tags: mariadb,db,centos
    yum: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"
